### ISSUE TITLE
[✍️ DevLog] / 220723_Sat

### ISSUE THREAD

**Issue by robin14dev** [robin14dev/local-festival#29]
### Todo
- [ ] 무한스크롤
- [x] 회원정보 수정 CSS
- [ ] db user column account를 email로 바꾸기
- [ ] 에러 발견, 무한렌더링으로 추후에 받아온 아이템을 찜한 후에 찜목록에 가보면 없슴 기본10개짜리인데 무한렌더링을 한번 해서 12번째 축제를 찜했을 때 찜 리스트를 가면 없슴, 그 받아온걸로 상태변경을 했는데 다른페이지로 넘어가면서 무한렌더링된게 날라가서 처음 10개로 렌더링 되는 것 같음.
### 오늘은 어떻게 프로젝트에 기여했나요?
- 
 ### 오늘의 프로젝트에서 힘든 점은 무엇인가요?
-  

```js
 // 코드를 첨부해도 좋습니다.
```

 ### 내일은 프로젝트에 기여하기 위해 무엇을 해야 하나요?
- [ ] Review CRUD 별점 상태관리 에러 핸들링하기
